/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
    IMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiReplay: typeof import('~icons/mdi/replay')['default']
    IMdiSendOutline: typeof import('~icons/mdi/send-outline')['default']
    IMdiSettings: typeof import('~icons/mdi/settings')['default']
    IMdiStop: typeof import('~icons/mdi/stop')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XBrand: typeof import('./src/components/XBrand.vue')['default']
    XButton: typeof import('./src/components/XButton.vue')['default']
    XCard: typeof import('./src/components/XCard.vue')['default']
    XChatView: typeof import('./src/components/XChatView.vue')['default']
    XDrawer: typeof import('./src/components/XDrawer.vue')['default']
    XEllipsis: typeof import('./src/components/XEllipsis.vue')['default']
    XEmpty: typeof import('./src/components/XEmpty.vue')['default']
    XInput: typeof import('./src/components/XInput.vue')['default']
    XMarkdown: typeof import('./src/components/XMarkdown.vue')['default']
    XMenu: typeof import('./src/components/XMenu.vue')['default']
    XMessage: typeof import('./src/components/XMessage.vue')['default']
    XMsg: typeof import('./src/components/XMsg.vue')['default']
    XSafeArea: typeof import('./src/components/XSafeArea.vue')['default']
    XSelect: typeof import('./src/components/XSelect.vue')['default']
    XSwitch: typeof import('./src/components/XSwitch.vue')['default']
    XTab: typeof import('./src/components/XTab.vue')['default']
    XTag: typeof import('./src/components/XTag.vue')['default']
    XThink: typeof import('./src/components/XThink.vue')['default']
    XWelcome: typeof import('./src/components/XWelcome.vue')['default']
  }
}
